eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    appname: localhost
 
microservice:
  payment-service:
    endpoint: http://PAYMENT-SERVICE/payment/dopay
microservice1:
  order-service:
    endpoint: http://ORDER-SERVICE/order/dobook

